version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: server.sh
      timeout: 300
      runas: ubuntu
