name: purpos_server
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: ./
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
          EOF

      - name: Install dependencies
        working-directory: ./
        run: |
          npm install && npm install --save-dev typescript@^4.5.4
          npm run build

      - name: zip distributions
        run: zip -r build.zip ./ ./appspec.yml ./server.sh

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://purposeevent/server/

      - name: deploy with AWS codeDeploy
        run: |
          aws deploy create-deployment \
          --application-name purpose_deploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name purpose_server \
          --s3-location bucket=purposeevent,bundleType=zip,key=server/build.zip \
